version: '3.5'

networks:
  app-network:
    driver: ${APP_NETWORK}

services:

# \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
# \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
# \\\\\\\\\\\\\\\\\\\ PRODUCTION ENVIRONMENT \\\\\\\\\\\\\\\\\
# \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
# \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

  # ------------------------------------------------------------
  # Nginx - Webserver
  # ------------------------------------------------------------
  nginx:
    image: nginx:mainline-alpine
    restart: unless-stopped
    container_name: nginx
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.docker/nginx/prod:/etc/nginx/conf.d:z
      - ./.docker/certbot/conf:/etc/letsencrypt:z
      - ./.docker/certbot/www:/var/www/certbot:z
    networks:
      - app-network

  # ------------------------------------------------------------
  # CERTBOT - SSL CERTIFICATION
  # ------------------------------------------------------------
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./.docker/certbot/conf:/etc/letsencrypt:z
      - ./.docker/certbot/www:/var/www/certbot:z

  # ------------------------------------------------------------
  # Node - Backend
  # ------------------------------------------------------------
  backend:
    build:
      context: ./.docker/build/node
      args:
        NODE_VERSION: ${BACKEND_NODE_VER}-alpine
    hostname: backend
    working_dir: /home/node/app
    volumes:
      - ./server:/home/node/app:z
    command:
      - sh
      - -c
      - npm ci && npm run start:${START_BACKEND_AS}
    depends_on:
      - redis
      - mongo
    networks:
      - app-network


  # ------------------------------------------------------------
  # Redis - Cache Management
  # ------------------------------------------------------------
  redis:
    image: redis:${REDIS_SERVER}-alpine
    hostname: redis
    # Apply custom arguments to redis startup
    command: redis-server ${REDIS_ARGS:- }
    environment:
      - REDIS_ARGS=${REDIS_ARGS:- }
    networks:
      - app-network


  # ------------------------------------------------------------
  # MongoDB - Database
  # ------------------------------------------------------------
  mongo:
    image: mongo:${MONGO_SERVER}
    hostname: mongo
    volumes:
      # Mount MongoDB Data directory
      - ./.docker/data/mongo:/data/db:z
    networks:
      - app-network


# \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
# \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
# \\\\\\\\\\\\\\\\\\ DEVELOPMENT ENVIRONMENT \\\\\\\\\\\\\\\\\
# \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
# \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

  # ------------------------------------------------------------
  # Nginx
  # ------------------------------------------------------------
  nginx_dev:
    image: nginx:mainline-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./.docker/nginx/dev:/etc/nginx/conf.d:z
    networks:
      - app-network


  # ------------------------------------------------------------
  # Redis
  # ------------------------------------------------------------
  redis_dev:
    image: redis:${REDIS_SERVER}-alpine
    hostname: redis_dev
    # Apply custom arguments to redis startup
    command: redis-server ${REDIS_ARGS:- }
    environment:
      - REDIS_ARGS=${REDIS_ARGS:- }
    ports:
      - ${LOCAL_LISTEN_ADDR}${REDIS_CONTAINER_PORT}:6379
    networks:
      - app-network


  # ------------------------------------------------------------
  # MongoDB
  # ------------------------------------------------------------
  mongo_dev:
    image: mongo:${MONGO_SERVER}
    hostname: mongo_dev
    ports:
      # [local-machine:]local-port:docker-port
      - ${LOCAL_LISTEN_ADDR}${MONGO_CONTAINER_PORT}:27017
    volumes:
      # Mount MongoDB Data directory
      - ./.docker/data/mongo:/data/db:z
    networks:
      - app-network
