version: '3.5'

networks:
  app-network:
    driver: ${APP_NETWORK}

services:
  # ------------------------------------------------------------
  # Nginx - Webserver
  # ------------------------------------------------------------
  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - ${BACKEND_CONTAINER_PORT}:80
    volumes:
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d:z
    depends_on:
      - backend
    networks:
      - app-network


  # ------------------------------------------------------------
  # Node - Backend
  # ------------------------------------------------------------
  backend:
    build:
      context: ./.docker/build/node
      args:
        NODE_VERSION: ${BACKEND_NODE_VER}-alpine
    hostname: backend
    working_dir: /home/node/app
    volumes:
      - ./server:/home/node/app:z
    command:
      - sh
      - -c
      - npm ci && npm run start:${START_BACKEND_AS}
    depends_on:
      - redis
      - mongo
    networks:
      - app-network


  # ------------------------------------------------------------
  # Redis - Cache Management
  # ------------------------------------------------------------
  redis:
    image: redis:${REDIS_SERVER}-alpine
    hostname: redis
    # Apply custom arguments to redis startup
    command: redis-server ${REDIS_ARGS:- }
    environment:
      - REDIS_ARGS=${REDIS_ARGS:- }
    networks:
      - app-network


  # ------------------------------------------------------------
  # MongoDB - Database
  # ------------------------------------------------------------
  mongo:
    image: mongo:${MONGO_SERVER}
    hostname: mongo
    volumes:
      # Mount MongoDB Data directory
      - ./.docker/data/mongo:/data/db:z
    networks:
      - app-network


# ------------------------------------------------------------
# ------------------------------------------------------------
# ------------------------------------------------------------


  # ------------------------------------------------------------
  # Redis for dev2
  # ------------------------------------------------------------
  redis_dev2:
    image: redis:${REDIS_SERVER}-alpine
    hostname: redis
    # Apply custom arguments to redis startup
    command: redis-server ${REDIS_ARGS:- }
    environment:
      - REDIS_ARGS=${REDIS_ARGS:- }
    ports:
      - ${LOCAL_LISTEN_ADDR}${REDIS_CONTAINER_PORT}:6379
    networks:
      - app-network


  # ------------------------------------------------------------
  # MongoDB for dev2
  # ------------------------------------------------------------
  mongo_dev2:
    image: mongo:${MONGO_SERVER}
    hostname: mongo
    ports:
      # [local-machine:]local-port:docker-port
      - ${LOCAL_LISTEN_ADDR}${MONGO_CONTAINER_PORT}:27017
    volumes:
      # Mount MongoDB Data directory
      - ./.docker/data/mongo:/data/db:z
    networks:
      - app-network
